2022-08-08 03:17:21,790 [88] ERROR FormBot.Helper.Logger - <log4net.Error>Exception during StringFormat: Index (zero based) must be greater than or equal to zero and less than the size of the argument list. <format>
 Controller : Base
 Action: KeepSessionAlive
 Message : An exception has been raised that is likely due to a transient failure. If you are connecting to a SQL Azure database consider using SqlAzureExecutionStrategy.
 InnerException : System.Data.Entity.Core.EntityException: The underlying provider failed on Open. ---> System.Data.Entity.Core.EntityException: An exception has been raised that is likely due to a transient failure. If you are connecting to a SQL Azure database consider using SqlAzureExecutionStrategy. ---> System.Data.SqlClient.SqlException: Database 'formbot_db_2020-04-10T06-40Z' on server 'formbot.database.windows.net' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{4BFCFD08-7A33-45F6-A5D5-6516FEBE9CD5}'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass4.<<ExecuteAsync>b__3>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<ExecuteAsyncImplementation>d__9`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<ExecuteAsyncImplementation>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.EntityClient.EntityConnection.<OpenAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.EntityConnection.<OpenAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<EnsureConnectionAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__3d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<ExecuteAsyncImplementation>d__9`1.MoveNext()
=================================================================================================================================================</format><args>{}</args></log4net.Error>
2022-08-08 03:17:21,817 [88] ERROR FormBot.Helper.Logger - <log4net.Error>Exception during StringFormat: Index (zero based) must be greater than or equal to zero and less than the size of the argument list. <format>Error Date: 2022-08-08 03:17:21 Controller: Base Action: KeepSessionAlive Error Line No:0 Error Message:Database 'formbot_db_2020-04-10T06-40Z' on server 'formbot.database.windows.net' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{4BFCFD08-7A33-45F6-A5D5-6516FEBE9CD5}'. Message : 
 InnerException : 
=================================================================================================================================================</format><args>{}</args></log4net.Error>
2022-08-08 11:16:58,534 [46] INFO  FormBot.Helper.Log - enter in writeError:08/08/2022 11:16:58
2022-08-08 11:16:58,534 [46] INFO  FormBot.Helper.Log - enter in writeError between:08/08/2022 11:16:58
2022-08-08 11:16:58,534 [46] ERROR FormBot.Helper.Log - Error for UserId : 691 08/08/2022 Column 'EntityName' does not belong to table Table. Message : Column 'EntityName' does not belong to table Table.
 InnerException : 
=================================================================================================================================================
2022-08-08 11:17:07,161 [96] INFO  FormBot.Helper.Log - enter in writeError:08/08/2022 11:17:07
2022-08-08 11:17:07,161 [96] INFO  FormBot.Helper.Log - enter in writeError between:08/08/2022 11:17:07
2022-08-08 11:17:07,161 [96] ERROR FormBot.Helper.Log - Error for UserId : 691 08/08/2022 Column 'EntityName' does not belong to table Table. Message : Column 'EntityName' does not belong to table Table.
 InnerException : 
=================================================================================================================================================
2022-08-08 12:21:00,295 [6] ERROR FormBot.Helper.Logger - <log4net.Error>Exception during StringFormat: Input string was not in a correct format. <format>
 Controller : Job
 Action: Index
 Message : c:\Users\PCA196\AppData\Local\Temp\Temporary ASP.NET Files\vs\0ba84d0f\5a4a7f93\App_Web__jobphotosnew.cshtml.145aa72b.9mznwerg.0.cs(4645): error CS1513: } expected
 InnerException : 
=================================================================================================================================================</format><args>{}</args></log4net.Error>
2022-08-08 12:21:00,328 [6] ERROR FormBot.Helper.Logger - <log4net.Error>Exception during StringFormat: Input string was not in a correct format. <format>Error Date: 2022-08-08 12:21:00 Controller: Job Action: Index Error Line No:0 Error Message:c:\Users\PCA196\AppData\Local\Temp\Temporary ASP.NET Files\vs\0ba84d0f\5a4a7f93\App_Web__jobphotosnew.cshtml.145aa72b.9mznwerg.0.cs(4645): error CS1513: } expected Message : 
 InnerException : 
=================================================================================================================================================</format><args>{}</args></log4net.Error>
2022-08-08 13:43:37,238 [7] ERROR FormBot.Helper.Logger - 
 Controller : Job
 Action: Index
 Message : d:\Projects\Formbot\SourceCode\FormBot01082017\FormBot.Main\Views\Job\_JobPhotosNew.cshtml(21): error CS0023: Operator '+' cannot be applied to operand of type 'string'
 InnerException : 
=================================================================================================================================================
2022-08-08 13:43:37,258 [7] ERROR FormBot.Helper.Logger - Error Date: 2022-08-08 13:43:37 Controller: Job Action: Index Error Line No:0 Error Message:d:\Projects\Formbot\SourceCode\FormBot01082017\FormBot.Main\Views\Job\_JobPhotosNew.cshtml(21): error CS0023: Operator '+' cannot be applied to operand of type 'string' Message : 
 InnerException : 
=================================================================================================================================================
2022-08-08 13:59:47,531 [53] INFO  FormBot.Helper.Log - enter in writeError:08/08/2022 13:59:47
2022-08-08 13:59:47,537 [53] INFO  FormBot.Helper.Log - enter in writeError between:08/08/2022 13:59:47
2022-08-08 13:59:47,537 [53] ERROR FormBot.Helper.Log - Error for UserId : 691 08/08/2022 Column 'EntityName' does not belong to table Table. Message : Column 'EntityName' does not belong to table Table.
 InnerException : 
=================================================================================================================================================
2022-08-08 14:27:04,576 [79] INFO  FormBot.Helper.Log - enter in writeError:08/08/2022 14:27:04
2022-08-08 14:27:04,576 [79] INFO  FormBot.Helper.Log - enter in writeError between:08/08/2022 14:27:04
2022-08-08 14:27:04,576 [79] ERROR FormBot.Helper.Log - Error for UserId : 691 08/08/2022 Column 'EntityName' does not belong to table Table. Message : Column 'EntityName' does not belong to table Table.
 InnerException : 
=================================================================================================================================================
